version: '3.1'

services:
#  mysql:
#    image: registry.lottefn.vn:5000/mysql:8.0.41
#    container_name: camunda-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: camunda
#      MYSQL_USER: camunda
#      MYSQL_PASSWORD: camunda
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  camunda:
    build: ./camunda
    container_name: camunda
    env_file:
      - .env
    environment:
      DB_DRIVER: ${CAMUNDA_DB_DRIVER}
      DB_URL: ${CAMUNDA_DB_URL}
      DB_USERNAME: ${CAMUNDA_DB_USERNAME}
      DB_PASSWORD: ${CAMUNDA_DB_PASSWORD}
    ports:
      - "8080:8080"

#  spring_app:
#    image: my-spring-app:latest
#    depends_on:
#      - mysql
#      - camunda
#    ports:
#      - "8082:8082"

#volumes:
#  mysql_data:
