server:
  port: 8888
jasypt:
  encryptor:
    password: Lotte@202$
    property:
      prefix: "ENC("
      suffix: ")"
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 200000
      pool-name: HikariPoolBooks
    username: bis
    password: HaK#bIs!lF2o18
    url: jdbc:oracle:thin:@//10.252.116.59:1521/bisdb
    driver-class-name: oracle.jdbc.OracleDriver

jwt:
  secret: 1ea7ab3a09c4dc5aaea0026ff82a4c857b968ab8a1a815095ebd4d9ec9dc5c46
  token:
    expiration: 24

cors:
  allowed-origins: http://localhost:3000


