version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_with_nginx
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: nhanph
      MINIO_ROOT_PASSWORD: Nhan21..
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=Nhan21..
      - MINIO_SECRET_KEY=Nhan21..
    depends_on:
      - minio
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge