server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.19:3302/timekeeping_face
    username: nhanph
    password: Nhan21..
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    generate-ddl: false
  kafka:
    bootstrap-servers: 192.168.1.19:9092
    consumer:
      group-id: timekeeping-detector
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "nhanph.timekeeping.common.dto"
  data:
    redis:
      host: 192.168.1.19
      port: 6379
      password: Nhan21..
      timeout: 60000
services:
  minio_service: http://192.168.1.19:8181/api/v1/file
  face_service: http://192.168.1.19:8005