version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: unless-stopped
    container_name: timekeeping_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data  # Lưu trữ dữ liệu Zookeeper ngoài container

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: unless-stopped
    container_name: timekeeping_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data  # Lưu trữ dữ liệu Kafka ngoài container

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    container_name: timekeeping_kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    volumes:
      - kafdrop-data:/var/lib/kafdrop  # Nếu muốn lưu trữ logs hoặc cấu hình Kafdrop ngoài container

volumes:
  zookeeper-data:
  kafka-data:
  kafdrop-data:  # Tạo volume cho Kafdrop (nếu cần)
